# -*- coding: utf-8 -*-
"""minerva_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GU8tAdH7pt24AGF7khIpt0Eq5WxI-06f
"""

!pip install transformers torch accelerate pandas openpyxl

from google.colab import files

files.upload()

!ls

import pandas as pd

adjectives_df = pd.read_excel("input_adjectives.xlsx")
sentences_df  = pd.read_excel("input_sentences.xlsx")

print(adjectives_df.head())
print(sentences_df.head())

#Minerva upload + verify tokenization
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_ID = "sapienzanlp/Minerva-7B-instruct-v1.0"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)
tokens = tokenizer.tokenize("anormale")
print(tokens)
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(token_ids)

def generate(prompt, max_new_tokens=128):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        temperature=0.0
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

"""Tentativo prompt 1

1) *Solo* *aggettivi*
"""

def adjectives_prompt1(lemma: str) -> bool:
    prompt = f"""Dato l'aggettivo "{lemma}",
    se una forma dell'aggettivo con uno dei seguenti prefissi:
    in-, im-, il-, ir-, dis-, a-, de-, s-, mis-,
    restituisci SOLO quella forma.

    Altrimenti, restituisci SOLO:
    NO.

    Nessuna spiegazione.
    """
    return generate(prompt)

adjectives_df["MINERVA_OUTPUT"] = adjectives_df["LEMMA"].apply(
    adjectives_prompt1
)

"""2) *Aggettivi in contesto*"""

def sentence_prompt1(sentence, lemma)
prompt = f"""Data la frase:

{sentence}

L'aggettivo "{lemma}" appare nella frase.

Se esiste una forma negativa dell'aggettivo con prefisso di negazione
(ad esempio: in-, im-, il-, ir-, dis-, a-, de-, s-, mis-),
riscrivi la frase usando quella forma.

Altrimenti, lascia la frase invariata.

Restituisci SOLO la frase modificata.
Nessuna spiegazione.
"""
    return generate(prompt, max_new_tokens=50)

"""Tentativo prompt 2

1) *Solo aggettivi*
"""

def adjectives_prompt2(lemma):
    prompt = f"""
    Aggettivo italiano: "{LEMMA}"

Esiste una forma negativa con prefisso
(in-, im-, il-, ir-, dis-, a-, de-, s-, mis-)?

Rispondi SOLO con:
- la forma negativa, oppure
- NO

"""
    return generate(prompt)

"""2) *Aggettivi in contesto*"""

def sentence_prompt2(sentence, lemma)
prompt = f"""Data la frase:

{sentence}

L'aggettivo "{lemma}" appare nella frase.

Se esiste una forma negativa dell'aggettivo con prefisso di negazione
(ad esempio: in-, im-, il-, ir-, dis-, a-, de-, s-, mis-),
riscrivi la frase usando quella forma.

Altrimenti, lascia la frase invariata.

Esempio:
Data la frase: "Scrivere è utile".
Esiste l'aggettivo: "inutile".
Restituisci: "Scrivere è inutile".


Restituisci SOLO la frase modificata.
Nessuna spiegazione.
"""
    return generate(prompt, max_new_tokens=50)